apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-shop-app-deployment
  labels:
    app: e-shop-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: e-shop-app
  template:
    metadata:
      labels:
        app: e-shop-app
    spec:
      containers:
      - name: e-shop-app-container
        image: pancikrango/e-shop-app-image:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 9091
        env:
          - name: POSTGRESQL_HOST
            value: postgres-e-shop-db
          - name: POSTGRES_DB
            value: e-shop
          - name: POSTGRES_USER
            value: wp
          - name: POSTGRES_PASSWORD
            value: wp123
          - name: PGPORT
            value: "5432"